# Generated by Django 4.2.5 on 2023-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_favorite_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color_code',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
