# Generated by Django 4.2.5 on 2023-09-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Ingredient',
        ),
    ]
