# Generated by Django 4.2.5 on 2023-09-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_picture_recipe_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite',
            new_name='recipe',
        ),
    ]
