# Generated by Django 4.2.5 on 2023-09-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_favorite_favorite_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
