# Generated by Django 4.2.5 on 2023-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients_recipe', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
    ]
