# Generated by Django 4.2.5 on 2023-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='ingredients_recipe', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
    ]
