# Generated by Django 4.2.5 on 2023-09-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_author_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
