# Generated by Django 4.2.5 on 2023-09-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_title_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
